# Makefile
# Include -g flag to get debugging information
# valgrind: memory check and produces a report
all: minstack 

minstack: minstack.cpp
	g++ -g --std=c++11 minstack.cpp -o minstack

clean:
	rm minstack 
